baseurl = "https://mikemc.netlify.com/"
languageCode = "en"
title = "Mike's test blog"
theme = "kiss"
copyright = "&copy; Michael McLaren 2017"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.sections_left]

[params.sections_right]

[params.features]

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Michael McLaren" # Site author's full name
authorEmail = "m.mclaren42@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = false # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "mikemc423"
github = "mmclaren42"
email = "m.mclaren42@gmail.com"
linkedin = ""
gitlab = ""
instagram = ""
codepen = ""
facebook = ""

[params.social.config]
platforms = ["twitter","github","email"]

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[params.fathomAnalytics]
rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

